### ISSUE TITLE
Improvement: language and subsite separation.

### ISSUE THREAD

**Issue by Yivan** [dachcom-digital/pimcore-lucene-search#18]
Hello,

I was asking me if the plugin can handle subsite and langage separation (for search, autocomplete and suggestion), so it send only result for the langage or subsite ?
Is there any way to configure it like this ?

If not, maybe it could be improved to handle multi-site and multi-langage case.

Thanks again for this wonderfull plugin very complete (i really liked the auto sugestion : )) like Google)

**Comment by solverat** [comment]
Yes, LuceneSearch respects languages, countries and domain restrictions. Just check the backend settings.

**Comment by Yivan** [comment]
I missed those settings. Great thanks a lot!
