### ISSUE TITLE
add more debug infos

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-lucene-search#30]
Sometimes, its very hard to debug Lucene Search. Therefore it would be nice to have more debug informations like:
 - I am currently crawling this site: $url
 - I am denying this site: $url cause of this regex: $url
 - I added this site $site to the index with this $language/$country (or whatever we can print here)

**Comment by solverat** [comment]
resolved with ad20ac99bb1c7298c14e421467ae05eec024baaa.
