### ISSUE TITLE
[LuceneSearch2] replace zf1/zend-search-lucene

### ISSUE THREAD

**Issue by solverat** [dachcom-digital/pimcore-lucene-search#34]
Tried already and had some conflicts with composer since pimcore requires 
`"zendframework/zend-servicemanager": "^3.2"` which relies on the `"zendframework/zend-stdlib": "^3.1"` package.

Since the ZendSearch packages requires `"zendframework/zend-stdlib": "2.*"` we're going to run into some conflicts.

**Comment by dpfaffenbauer** [comment]
not even sure if ZendSearch is still supported by Zend?

**Comment by solverat** [comment]
since the zf1 version works smoothly with php7, ZendSearch does not work with php7 and has been abandoned. There is an alternative ([pucene/pucene](https://github.com/pucene/pucene)) which is not ready for production though.

**Comment by solverat** [comment]
alternative: https://github.com/teamtnt/tntsearch

**Comment by dpfaffenbauer** [comment]
I'd stick with Zend Lucene, its kinda bullet proof and field tested, don't you think?

**Comment by solverat** [comment]
We just tested the Lucene Extension on PHP 7.2 without any issues. Since we're quite happy with it and also had no issues with large indexes (> 20.000 pages with ease and still really fast) we'll keep with Zend Lucene.
