### ISSUE TITLE
[LuceneSearch1] multiple start urls for crawling

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-lucene-search#42]
Multiple Start Urls for crawling result in having only indexed the latest one. For example:

```
b2b.domain.com
www.domain.com
test.domain.com
```

LuceneSearch crawls these domains, but only indexes the last one.

**Comment by dpfaffenbauer** [comment]
Doesn't seem to happen for v2, as it tries to open an existing index before doing anything else:

https://github.com/dachcom-digital/pimcore-lucene-search/blob/master/src/LuceneSearchBundle/Task/Parser/ParserTask.php#L755

in comparison: v1 always creates the index:

https://github.com/dachcom-digital/pimcore-lucene-search/blob/pimcore4/lib/LuceneSearch/Model/Parser.php#L1125

**Comment by solverat** [comment]
fixed with #44 .
