### ISSUE TITLE
Having some issues with search form

### ISSUE THREAD

**Issue by patrickfabrizius** [dachcom-digital/pimcore-lucene-search#46]
The instructions state that I should setup a view script containing: 
`$this->action('find', 'frontend', 'LuceneSearch', array('viewScript' => 'frontend/find.php'));
`
This yields the following error: 

script 'frontend/find.php' not found in path `(/Users/patrick/Sites/externt/lucenetest/plugins/LuceneSearch/views/scripts/:/Users/patrick/Sites/externt/lucenetest/website/views/layouts/:/Users/patrick/Sites/externt/lucenetest/website/views/scripts/:./views/layouts/:./views/scripts/)`

Just copying the contents of plugins/LuceneSearch/views/scripts/search/find.php won't do since it's useless without it's controller .. 

What am I missing?

**Comment by solverat** [comment]
@patrickfabrizius please use the [pimcore4 board](https://groups.google.com/forum/#!forum/pimcore) for support questions. also the pimcore4 version is not supported anymore.
