### ISSUE TITLE
Use APPEND_FILE flag instead of re-writing the complete logfile

### ISSUE THREAD

**Issue by gadget60** [dachcom-digital/pimcore-lucene-search#51]
Is there a specific reason why you read the complete log file in order to add a line to it? This seems to be much overhead once the log file grows bigger - why not just something like:

```php
$current = date('d.m.Y H:i') . '|' . $this->getRealLevel($level) . '|' . $message . "\n";
file_put_contents($file, $current, FILE_APPEND);
```
https://github.com/dachcom-digital/pimcore-lucene-search/blob/9d9bd9deebac2b58cad6faf126a09191b6d984ea/src/LuceneSearchBundle/Logger/Logger.php#L35

**Comment by solverat** [comment]
hey @gadget60 You're absolutely right :), i'll implement that as soon as possible.
