### ISSUE TITLE
Crawl Error on fresh Lucene Install - Pimcore 5

### ISSUE THREAD

**Issue by ejsenn** [dachcom-digital/pimcore-lucene-search#52]
Hi, first of all - sorry for re-opening but in my case it needs to be :( I'm running pimcore 5, everything works well and I installed lucene using the composer, activated at the extension manager and so on. I placed the lucene config from above example at src/Appbundle/Resources/config/pimcore/config.yml as suggested but if i start a manual crawl on the console I still having the Error "no valid task iterators defined!"

any ideas ? thanks in advance ! kind regards

**Comment by ritunrtc** [comment]
all required values need to be in the config.yml file. It will look like :
lucene_search:
    enabled: true
    fuzzy_search_results: true
    search_suggestion: true
    own_host_only:  false
    seeds: ['http://xxx/']
    sitemap:
        render: true
    locale:
        ignore_language:  true
        ignore_country: true
    restriction:
            enabled:  false
    filter:
        valid_links:  ['@^http://xxx.*@i']
    crawler:
        content_max_size: 4
    view:
        max_per_page: 10

**Comment by ejsenn** [comment]
hi ritunrtc,

thanks for your answer ... please find below my full config-file. next question. is this "src/AppBundle/Resources/config/pimcore/config.yml" the corrent file and path ?

----> config.yml

imports:
    - { resource: security.yml }

pimcore:
    # we override the generated user model with a custom class which implements the UserInterface
    models:
        class_overrides:
            'Pimcore\Model\DataObject\User': 'AppBundle\Model\DataObject\User'

lucene_search:
    enabled: true
    sitemap:
        render: false
    fuzzy_search_results: false
    search_suggestion: true
    seeds:
        - 'https://www.soul4business.com'
    filter:
        valid_links:
            - '@^https://www.soul4business.com.*@i'
    view:
        max_per_page: 10
    crawler:
        content_max_size: 4
        content_start_indicator: ''
        content_end_indicator: ''

**Comment by ritunrtc** [comment]
yes

**Comment by ejsenn** [comment]
Ok so I don't understand what the problem is with it ?! Any ideas ? Thanks in advance ...
