### ISSUE TITLE
Cannot start crawl without existing state.cnf

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-lucene-search#55]
If there is no state.cnf, LuceneSearch fails with following error:
```
invalid state config slot "finished"
```

This is due to a missing state.cnf. But there is currently no state.cnf, because LuceneSearch support has just been deployed.

**Comment by aarongerig** [comment]
The same issue for me as well. Is there currently a workaround for this?

**Comment by dpfaffenbauer** [comment]
@aarongerig Yes: uploading the state.cnf manually and add it to your deployer configuration as shared file. For example, this is my deployer config for LuceneSearch:

```
set('shared_files', [
    'var/bundles/LuceneSearchBundle/state.cnf'
]);
set('shared_dirs', [
    'var/bundles/LuceneSearchBundle/index',
    'var/bundles/LuceneSearchBundle/site-map'
]);
```

Its important to share LuceneSearchBundle through different releases, otherwise you would have to re-index on every release.

**Comment by aarongerig** [comment]
@dpfaffenbauer Thanks, I will try it with that!
