### ISSUE TITLE
Ajax AutoComplete example

### ISSUE THREAD

**Issue by ritunrtc** [dachcom-digital/pimcore-lucene-search#60]
I followed the guide to implement the search page with  ajax autoComplete 
when ,I search, I get the following error :

Symfony\Component\Debug\Exception\ContextErrorException
in vendor\dachcom-digital\lucene-search\src\LuceneSearchBundle\Controller\AutoCompleteController.php (line 26)
foreach ($terms as $term) {            $t = $term->text;

Any help ?

**Comment by solverat** [comment]
i guess there is something completely wrong with your setup (installed via composer? all dependency installed? enabled in extension manager?). please follow the installation instructions, ask in gitter for help first and finally, if it's really a potential bug, post it here on github.
