### ISSUE TITLE
Abstract Persisting Layer

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-lucene-search#80]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | yes - no
| RFC?             | yes

It should be possible to also use other storage engines to persist, like Solr or ElasticSearch. Having a abstraction layer would solve that. Per Default Lucene-Search (which then should be renamed as well?) is the default implementation. Every other implementation can be done using separated packages.

**Comment by solverat** [comment]
Well be possible with the new [dynamic search bundle](https://github.com/dachcom-digital/pimcore-dynamic-search).
