### ISSUE TITLE
Integration with ProcessManager?

### ISSUE THREAD

**Issue by dpfaffenbauer** [dachcom-digital/pimcore-lucene-search#84]
| Q                | A
| ---------------- | -----
| Bug report?      | no
| Feature request? | yes
| BC Break report? | no
| RFC?             | yes

I think a integration with ProcessManager would be great.

https://github.com/dpfaffenbauer/ProcessManager

What do you think?

**Comment by solverat** [comment]
This could be "maybe" feature for the dynamic-search-bundle. But i think it's a tricky one. The page crawling process for example cannot  provide any "calculated end" therefor there is no predefined step range. However, we'll not implement any new features into this bundle.  Thanks!

**Comment by dpfaffenbauer** [comment]
true. But Process Manager will support tasks without estimated ends in the future as well. So, once SearchBundle is done, I will create a PR ok?
