### ISSUE TITLE
Multiple index on multiple microsites

### ISSUE THREAD

**Issue by tobiasfeldmethwalter** [dachcom-digital/pimcore-lucene-search#86]
Is it possible to set the search so that there is a separate search index per microsite?

**Comment by solverat** [comment]
Hey @tobiasfeldmethwalter. No, currently everything gets stored in the same index. The Lucene Database is able to handle very large index files so mostly there is nothing to worry about. 

It's possible to add some custom flags to your index document to provide site-based search content, e.g. user query on `page a` should only search in documents with flag `page-a`.

We're also working on a complete new search engine (dynamic-search-bundle), which is able to handle multiple indexes.

**Comment by tobiasfeldmethwalter** [comment]
Hello @solverat,
Thank you for the faster feedback.
I just wanted to install and try the dynamic-search-bundle. Unfortunately, I get the message "The requested package dachcom-digital / search could not be found in any version, there may be a typo in the package name."
The project is on Pimcore version 5.6.6
Thanks for info about this bug
many Greetings
